[package]
name = "ross_server"
version = "0.1.0"
authors = ["Parsa Ghadimi <qti3eqti3e@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.10.0"
actix-web = "3.1.0"
actix-rt = "1.1.1"
actix-web-actors = "3.0.0"
rocksdb = "0.15.0"
bincode = "1.3.1"
serde = "1.0.117"
rand = "0.7.3"
